#!/bin/bash

# ZYBO Z7-20 SD Card Builder Script
# Automatically formats and prepares a bootable SD card
# Copies BOOT.BIN and image.ub to the boot partition
# Author: Generated by ChatGPT

set -e

BOOTFILE="BOOT.BIN"
IMAGEFILE="image.ub"

# Locate BOOT.BIN and image.ub
if [[ ! -f "$BOOTFILE" ]] || [[ ! -f "$IMAGEFILE" ]]; then
  echo "ERROR: BOOT.BIN or image.ub not found in current directory!"
  exit 1
fi

echo "[INFO] Searching for removable SD card device..."
DEVICE=$(lsblk -o NAME,RM,SIZE,MODEL | grep -E '^sd[a-z]' | awk '$2 == 1 { print $1 }' | head -n1)

if [[ -z "$DEVICE" ]]; then
  echo "ERROR: No removable SD card found."
  exit 1
fi

DEV="/dev/$DEVICE"
echo "[INFO] SD card detected: $DEV"

read -p "Are you sure you want to erase and reformat $DEV? This will destroy all data on it. (yes/NO): " CONFIRM
[[ "$CONFIRM" == "yes" ]] || exit 1

echo "[INFO] Unmounting any mounted partitions on $DEV..."
sudo umount ${DEV}?* || true

echo "[INFO] Creating new partition table..."
sudo parted $DEV mklabel msdos --script

echo "[INFO] Creating boot partition..."
sudo parted $DEV mkpart primary fat32 1MiB 128MiB --script
sudo parted $DEV set 1 boot on --script

echo "[INFO] Creating rootfs partition..."
sudo parted $DEV mkpart primary ext4 128MiB 100% --script

echo "[INFO] Formatting partitions..."
BOOTPART="${DEV}1"
ROOTPART="${DEV}2"
sudo mkfs.vfat -F 32 $BOOTPART -n BOOT
sudo mkfs.ext4 $ROOTPART -L ROOTFS

echo "[INFO] Mounting partitions..."
mkdir -p /tmp/boot /tmp/rootfs
sudo mount $BOOTPART /tmp/boot
sudo mount $ROOTPART /tmp/rootfs

echo "[INFO] Copying BOOT.BIN and image.ub to boot partition..."
sudo cp BOOT.BIN /tmp/boot/
sudo cp image.ub /tmp/boot/

echo "[INFO] Syncing and unmounting..."
sync
sudo umount /tmp/boot
sudo umount /tmp/rootfs
rm -rf /tmp/boot /tmp/rootfs

echo "[DONE] SD card is ready to boot on the ZYBO Z7-20."
